vich_uploader:
    db_driver: orm

    mappings:
        picture_file:
            uri_prefix: /assets/uploads/
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
